### ISSUE TITLE
Machine.ls() generate buggy last entry `{'Name': u''}`

### ISSUE THREAD

**Issue by eagafonov** [gijzelaerr/python-docker-machine#13]
Machine.ls() generate buggy last entry `{'Name': u''}`

```
In [18]: machine.Machine().ls()
Out[18]: 
[{'Active': '-', 'Name': 'python-docker-machine', .... },
 {'Active': '-', 'Name': 'swarm-1', .... },
 {'Active': '-', 'Name': 'swarm-2',... },
 {'Active': '-', 'Name': 'swarm-3', .... },
 {'Name': ''}]
```
It comes from empty line after `stdout.split("\n")` at https://github.com/gijzelaerr/python-docker-machine/blob/188e84fc6845386f26db758f763d771175375265/machine/machine.py#L149

```
In [15]: '1\n2\n'.split('\n')
Out[15]: ['1', '2', '']
```

lines split result need to filtered in order to drop last
empty-string-entry

PR will come shortly

**Comment by gijzelaerr** [comment]
merged, thanks!
